apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gitea 
  namespace: gitea
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: gitea
  template:
    metadata: 
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:latest
        ports:
        - containerPort: 3000
          name: http 
        - containerPort: 22
          name: ssh 
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"  
        - name: GITEA__server__ROOT_URL
          value: "http://192.168.1.201:3000/"
        - name: GITEA__database__DB_TYPE
          value: "sqlite3"
        volumeMounts:
        - name: gitea-data
          mountPath: /data
      volumes:
      - name: gitea-data
        PersistentVolumeClaim: 
          claimName: gitea-pvc

        
---
apiVersion: v1 
kind: Service
metadata:
  name: gitea-svc
  namespace: gitea
spec: 
  type: LoadBalancer
  selector: 
    app: gitea
  LoadBalancerIP: 192.168.1.201
  ports:
  - name: http 
    port: 3000
    targetPort: 3000
  - name: ssh
    port: 22
    targetPort: 22 